config/routes.rb
Rails.application.routes.draw do

  root                        to: 'users#home'

  # User routes
  post   '/users',            to: 'users#create'
  get    '/users/new',        to: 'users#new',        as: 'new_user'
  get    '/users/:id/edit',   to: 'users#edit',       as: 'edit_user'
  get    '/users/:id',        to: 'users#show',       as: 'user'
  patch  '/users/:id',        to: 'users#update',     as: 'update_user'
  delete '/users/:id',        to: 'users#destroy'

  # Entry routes
  get    '/entries',          to: 'entries#index'
  post   '/entries',          to: 'entries#create'
  get    '/entries/new',      to: 'entries#new',      as: 'new_entry'
  get    '/entries/:id/edit', to: 'entries#edit',     as: 'edit_entry'
  get    '/entries/:id',      to: 'entries#show',     as: 'show_entry'
  patch  '/entries/:id',      to: 'entries#update',   as: 'update_entry'
  delete '/entries/:id',      to: 'entries#destroy',  as: 'delete_entry'

  # Comments
  get    '/comments',         to: 'comments#index'
  get    '/comments/new',     to: 'comments#new',     as: 'new_comment'
  get    '/comments/:id',     to: 'comments#show',    as: 'comment'
  post   '/comments',         to: 'comments#create'
  delete '/comments/:id',     to: 'comments#destroy', as: 'delete_comment'

  # Session routes
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  get     '/logout',          to: 'sessions#destroy'
  delete  '/logout',          to: 'sessions#destroy'

  # Search forecast endpoints
  get     '/potato',          to: 'forecasts#by_geolocation'
  get     '/eggplant',        to: 'forecasts#by_search'

  # match "*path", to: 'application#page_not_found', via: :all

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authorize!

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def destroy
    @comment.destroy
    redirect_to entries_path
  end

  def create
    commentable = commentable_type.constantize.find(commentable_id)
    @comment = Comment.build_from(commentable, current_user.id, body)

    respond_to do |format|
      if @comment.save
        make_child_comment
        format.html { redirect_to(:back, :notice => 'Comment was successfully added.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type, :comment_id)
  end

  def commentable_type
    comment_params[:commentable_type]
  end

  def commentable_id
    comment_params[:commentable_id]
  end

  def comment_id
    comment_params[:comment_id]
  end

  def body
    comment_params[:body]
  end

  def make_child_comment
    return "" if comment_id.blank?

    parent_comment = Comment.find comment_id
    @comment.move_to_child_of(parent_comment)
  end
end

app/views/comments/_form.html.erb
<%= form_for @new_comment, class: 'ui form' do |f| %>
  <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
  <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
  <div class="field">
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= button_tag(class: 'ui submit button') do %>
      <i class="talk icon"></i> Comment
    <% end %>
  </div>
<% end %>

app/views/comments/_reply.html.erb
<% comments.each do |comment| %>
  <div class="comment">
    <div class='content'>
      <a class="avatar"><%= image_tag(comment.user.avatar.url(:thumb), class: 'ui avatar image') %></a>
      <div class='comment-wrapper'>
        <a class="author"><%= comment.user.name%></a>
        <div class="metadata">
          <span class="date"><%= time_ago_in_words(comment.created_at) %> ago</span>
        </div>
        <div class='text'><%=comment.body %></div>
      </div>
      <div class="actions">
        <a class="reply">reply</a>
        <% if current_user?(comment.user)%>
          <%= link_to 'delete', comment, method: :delete %>
        <% end %>
      </div>

      <%= form_for @new_comment, class: 'ui reply form' do |f|%>
        <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
        <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
        <%= f.hidden_field :comment_id, value: comment.id %>
        <div class="field toggle-reply"><%= f.text_area :body %></div>
        <div class="field toggle-reply">
          <%= button_tag( type: 'submit', class: 'ui submit button') do %>
            <i class="reply icon"></i> Reply
          <% end %>
        </div>
      <% end %>
    </div>

    <div class= "reply">
      <%= render partial: "comments/reply", locals: {comments: comment.children} %>
    </div>

<% end %>

app/views/comments/_template.html.erb
<div class="ui threaded comments">
  <h3 class="ui dividing header">Comments</h3>
  <div class="comments-container">
    <%= render partial: "comments/reply", locals: {comments: commentable.root_comments} %>
  </div>
  <%= render partial: "comments/form", locals: {new_comment: new_comment} %>
</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>