config/routes.rb
Rails.application.routes.draw do

  root                        to: 'users#home'

  # User routes
  post   '/users',            to: 'users#create'
  get    '/users/new',        to: 'users#new',        as: 'new_user'
  get    '/users/:id/edit',   to: 'users#edit',       as: 'edit_user'
  get    '/users/:id',        to: 'users#show',       as: 'user'
  patch  '/users/:id',        to: 'users#update',     as: 'update_user'
  delete '/users/:id',        to: 'users#destroy'

  # Entry routes
  get    '/entries',          to: 'entries#index'
  post   '/entries',          to: 'entries#create'
  get    '/entries/new',      to: 'entries#new',      as: 'new_entry'
  get    '/entries/:id/edit', to: 'entries#edit',     as: 'edit_entry'
  get    '/entries/:id',      to: 'entries#show',     as: 'show_entry'
  patch  '/entries/:id',      to: 'entries#update',   as: 'update_entry'
  delete '/entries/:id',      to: 'entries#destroy',  as: 'delete_entry'

  # Comments
  get    '/comments',         to: 'comments#index'
  get    '/comments/new',     to: 'comments#new',     as: 'new_comment'
  get    '/comments/:id',     to: 'comments#show',    as: 'comment'
  post   '/comments',         to: 'comments#create'
  delete '/comments/:id',     to: 'comments#destroy', as: 'delete_comment'

  # Session routes
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  get     '/logout',          to: 'sessions#destroy'
  delete  '/logout',          to: 'sessions#destroy'

  # Search forecast endpoints
  get     '/potato',          to: 'forecasts#by_geolocation'
  get     '/eggplant',        to: 'forecasts#by_search'

  # match "*path", to: 'application#page_not_found', via: :all

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user

  has_attached_file :avatar, styles: { medium: "300x300>", large: "1000x1000>" }, default_url: "",
        :storage => :cloudinary,
        :path    => ':id/:style/:filename'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  acts_as_commentable
  has_many :comments

  validates :user_id, presence: true
  validates :caption, presence: true, length: { maximum: 50 }
  validates :location, presence: true

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry,    only: [:edit, :destroy, :show, :update ]
  before_action :logged_in?,   only: [:edit, :destroy, :create,       :index, :show]
  before_action :correct_user, only: [:edit, :destroy]

  # GET /entries
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  def show
    @new_comment = Comment.build_from(@entry, current_user.id, "")
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  def create
    @entry = current_user.entries.build(entry_params)
    if @entry.save
      flash[:success] = "Posted!"
      redirect_to entries_path
    else
      redirect_to user_path(current_user)
    end
  end

  # PATCH/PUT /entries/1
  def update
    if @entry.update_attributes(entry_params)
      flash[:success] = "Entry updated"
      redirect_to show_entry_path
    else
      flash[:error]
      render 'edit'
    end
  end

  # DELETE /entries/1
  def destroy
    @entry.destroy
    redirect_to user_path(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params.require(:entry).permit(:caption, :location, :avatar, :user_id)
    end

    def correct_user
      @entry = current_user.entries.find_by(id: params[:id])
      redirect_to root_url if @entry.nil?
    end

end

app/views/entries/edit.html.erb
<div class='ui container'>
  <%= render 'layouts/header' %>

  <h2 class='ui centered header'>Edit Entry</h2>

  <div id="target"></div>

  <div class='ui form edit-entry'>
    <div class='fields'>
      <%= form_for :entry, method: :patch, url: {action: 'update'}, :html => {:class => "align-form"} do |f| %>
        <%= f.hidden_field :user_id %>

        <div class='field'>
          <%= f.label :image %>
          <%= f.file_field :avatar, id: 'pictureInput', requitred: true %>
        </div>

        <div class="field">
          <%= f.label :caption %>
          <div class='ui left icon input'>
            <%= f.text_field :caption %>
            <i class="talk outline icon"></i>
          </div>
        </div>

        <div class="field">
          <%= f.label :location %>
          <div class='ui left icon input'>
            <%= f.text_field :location %>
            <i class="location arrow icon"></i>
          </div>
        </div><br>

        <div class="actions">
          <%= f.submit "OK", class: "ui button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/entries/index.html.erb
<div class='ui container'>
  <%= render 'layouts/header' %>

  <div class='ui stackable three column grid container'>
    <% @entries.each do |entry| %>
      <div class='column'>
        <div class="ui segment">
          <%if entry.avatar.blank? %>
            <%= image_tag('https://semantic-ui.com/images/wireframe/square-image.png') %>
          <% else %>
            <%= image_tag(entry.user.avatar.url(:thumb), class: 'ui avatar image') %>
          <% end %>
            <%= link_to user_path(entry.user) do %>
                <%= entry.user.name %>
              <% end %> <span> <%= time_ago_in_words(entry.created_at) %> ago</p>
            <%= link_to show_entry_path(entry) do %>
              <%= image_tag(entry.avatar.url(:large), class: 'ui medium rounded image') %>
            <% end %><br>
          <div class="content">
            <h3 class='ui centered header'><%= entry.caption %></h3>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/entries/new.html.erb
<div class='ui container'>
  <%= render 'layouts/header' %>

  <h2 class='ui centered header'>New Entry</h2>

  <div id="target"></div>

  <div class='ui form new_entry'>
    <div class='fields'>
      <%= form_for [@entry.user, @entry], :html => {:class => "align-form"} do |f| %>
        <%= f.hidden_field :user_id %>

        <div class='field'>
          <%= f.label :image %>
          <%= f.file_field :avatar, id:'pictureInput', required: true %>
        </div>

        <div class="field">
          <%= f.label :caption %>
          <div class='ui left icon input'>
            <%= f.text_field :caption %>
            <i class="talk outline icon"></i>
          </div>
        </div>

        <div class="field">
          <%= f.label :location %>
          <div class='ui left icon input'>
            <%= f.text_field :location %>
            <i class="location arrow icon"></i>
          </div>
        </div><br>

        <div class="actions">
          <%= f.submit "OK", class: "ui button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/entries/show.html.erb
<div class='ui container'>
  <%= render 'layouts/header' %>

  <div class='show-header'>
    <%if @entry.user.avatar.blank? %>
      <%= image_tag('https://semantic-ui.com/images/avatar/large/elliot.jpg', class:'ui avatar image') %>
    <% else %>
      <%= image_tag(@entry.user.avatar.url(:thumb), class: 'ui avatar image') %>
    <% end %>
    <%= link_to user_path(@entry.user) do %>
      <%= @entry.user.name %>
    <% end %>  <span><%= @entry.created_at.strftime("%m/%d/%Y") %></span>
    <% if current_user?(@entry.user) %>
      <span class='show-buttons'>
        <%= link_to edit_entry_path(@entry) do %>
          <div class='link item'><i class="write large icon"></i></div>
        <% end %>
        <%= link_to delete_entry_path(@entry), method: :delete do %>
          <div class='link item'><i class="trash large icon"></i></div>
        <% end %>
      </span>
    <% end %>
  </div>

  <%= image_tag(@entry.avatar.url(:large), class: 'shadow ui centered large rounded image') %>

  <h2 class="ui header" id="img-header" >
    <div class="content">
      <%= @entry.caption %>
      <div class="sub header">
        <a id='map-modal' href='#'>
          <%= @entry.location %>
        </a>
      </div>
    </div>
  </h2>

  <%= render partial: "comments/template", locals: {commentable: @entry, new_comment: @comment} %>

  <div class="ui basic modal">
    <div class="ui icon header">
      <i class="map icon"></i>
      <%= @entry.location %>
    </div>
    <div class="content">
      <iframe width="100%" height="350" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/search?q=<%= @entry.location %>&key=AIzaSyBmkOMQR7DSJ1IP7y6Bg3Uoxq4JeZH4MjM" allowfullscreen></iframe>
    </div>
    <div class="ui icon header">
      <i class="moon icon"></i>
      Today's Forecast
    </div>
    <div class="forecast content">
    </div>
    <div class="actions">
      <div class="ui white ok inverted button">
        <i class="checkmark icon"></i>
        COOL
      </div>
    </div>
  </div>
</div>