config/routes.rb
Rails.application.routes.draw do

  root                        to: 'users#home'

  # User routes
  post   '/users',            to: 'users#create'
  get    '/users/new',        to: 'users#new',        as: 'new_user'
  get    '/users/:id/edit',   to: 'users#edit',       as: 'edit_user'
  get    '/users/:id',        to: 'users#show',       as: 'user'
  patch  '/users/:id',        to: 'users#update',     as: 'update_user'
  delete '/users/:id',        to: 'users#destroy'

  # Entry routes
  get    '/entries',          to: 'entries#index'
  post   '/entries',          to: 'entries#create'
  get    '/entries/new',      to: 'entries#new',      as: 'new_entry'
  get    '/entries/:id/edit', to: 'entries#edit',     as: 'edit_entry'
  get    '/entries/:id',      to: 'entries#show',     as: 'show_entry'
  patch  '/entries/:id',      to: 'entries#update',   as: 'update_entry'
  delete '/entries/:id',      to: 'entries#destroy',  as: 'delete_entry'

  # Comments
  get    '/comments',         to: 'comments#index'
  get    '/comments/new',     to: 'comments#new',     as: 'new_comment'
  get    '/comments/:id',     to: 'comments#show',    as: 'comment'
  post   '/comments',         to: 'comments#create'
  delete '/comments/:id',     to: 'comments#destroy', as: 'delete_comment'

  # Session routes
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  get     '/logout',          to: 'sessions#destroy'
  delete  '/logout',          to: 'sessions#destroy'

  # Search forecast endpoints
  get     '/potato',          to: 'forecasts#by_geolocation'
  get     '/eggplant',        to: 'forecasts#by_search'

  # match "*path", to: 'application#page_not_found', via: :all

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://www.ameristarcoil.com/Other/ameristarcoilCOM/imgs/placeholder_user.png",
        :storage => :cloudinary, 
        :path    => ':id/:style/:filename'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :entries, dependent: :destroy
  has_many :comments

  validates :name, :presence => true, length: { maximum: 255 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,     only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [       :edit, :update]
  before_action :logged_in?,   only: [:show, :edit]

  def home
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end


  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Stellar!"
      redirect_to @user
    else
      redirect_to 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :bio, :email, :password, :avatar)
    end

    def correct_user
      redirect_to(root_path) unless current_user?(@user)
    end

end

app/views/users/edit.html.erb
<div class='ui container'>
  <%= render 'layouts/header' %>

  <h2 class='ui centered header edit-profile'>Edit Profile</h3>

  <div id="target"></div>

  <div class='ui form'>
    <div class='fields'>
      <%= form_for @user, :html => {:class => "align-form"} do |f| %>

        <div class='field'>
          <%= f.label :image %>
          <%= f.file_field :avatar, id: 'pictureInput', requitred: true %>
        </div>

        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <%= f.label :bio %>
          <%= f.text_area :bio %>
        </div>

        <div class="field">
          <%= f.label :email %>
          <div class='ui left icon input'>
            <%= f.email_field :email %>
            <i class="mail icon"></i>
          </div>
        </div>

        <div class="field">
          <%= f.label :password %>
          <div class='ui left icon input'>
            <%= f.password_field :password %>
            <i class="lock icon"></i>
          </div>
        </div><br>

        <div class="actions">
          <%= f.submit "OK", class: "ui button" %>
          <%= link_to @user, method: :delete, class: 'ui button' do %>
            <i class="trash large icon"></i> Account
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/home.html.erb
<div class="video-background">
  <div class="video-foreground">
    <iframe id="vid-bg" src="https://www.youtube.com/embed/PrrHve14fAA?start=11&end=26controls=0&showinfo=0&rel=0&autoplay=1&loop=1&playlist=PrrHve14fAA" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

<div class='content-container'>
  <div class='ui container'>
    <h1 class='ui center aligned header' id='stellar'>
      <%= link_to root_path do %>
        Stellar
      <% end %>
    </h1>
    <div class="ui secondary  menu">
      <% if logged_in? %>
        <%= link_to entries_path do %>
          <div class='link item'><i class="grid layout large icon"></i></div>
        <% end %>
        <%= link_to current_user do %>
          <div class='link item'><i class="user large icon"></i></div>
        <% end %>
        <%= link_to new_entry_path(current_user) do %>
          <div class='link item'><i class="plus large icon"></i></div>
        <% end %>
        <%= link_to logout_path, method: "delete" do %>
          <div class='link item'><i class="sign out large icon"></i></div>
        <% end %>

      <% else %>
        <%= link_to login_path do %>
          <button class='ui button'> Sign In </button>
        <% end %>

        <%= link_to new_user_path do %>
          <button class='ui button'> Sign Up </button>
        <% end %>
      <% end %>

    <div class="right menu">
      <button class="item" onclick="getLocation();" data-tooltip="Click Me" data-position="top left" data-inverted="">
        <i class="location arrow large icon"></i>
      </button>
      <form class='ui form' id='forecast-search'>
        <div class="ui icon input">
          <input type="text" placeholder="Search..." id="location">
          <i class="search link icon"></i>
        </div>
      </form>
    </div>
  </div>

    <div class="ui inverted dimmer">
      <div class="ui large text loader">Loading</div>
    </div>
    <div id='results'></div>
  </div>
</div>

app/views/users/new.html.erb
<br><br><%= render 'layouts/header' %>

<h2 class='ui centered header'>Create Account</h2>

<div class='ui form'>
  <div class='fields'>
    <%= form_for @user, :html => {:class => "align-form"} do |f| %>

      <div class="field">
        <%= f.label :name %>
        <div class='ui left icon input'>
          <%= f.text_field :name %>
          <i class="add user icon"></i>
        </div>
      </div>

      <div class="field">
        <%= f.label :email %>
        <div class='ui left icon input'>
          <%= f.text_field :email %>
          <i class="mail icon"></i>
        </div>
      </div>

      <div class="field">
        <%= f.label :password %>
        <div class='ui left icon input'>
          <%= f.password_field :password %>
          <i class="lock icon"></i>
        </div>
      </div><br>

      <div class="actions">
        <%= f.submit "OK", class: "ui button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='ui container'>
  <%= render 'layouts/header' %>

  <div class="ui stackable grid container">
    <div class="six wide column">
      <div class="ui card">
        <div class="image">
          <%if @user.avatar.blank? %>
            <%= image_tag('https://semantic-ui.com/images/avatar/large/elliot.jpg') %>
          <% else %>
            <%= image_tag(@user.avatar.url(:medium)) %>
          <% end %>
        </div>
        <div class="content">
          <span class='header'><%= @user.name %></span>
          <div class="meta">
            Joined on <%= @user.created_at.strftime("%m/%d/%Y") %>
          </div>
          <div class="bio">
            <%= @user.bio %>
          </div>
        </div>
        <% if current_user?(@user) %>
          <div class="extra content">
            <%= link_to edit_user_path(@user) do %>
              <div class='right floated'><i class="write large icon"></i></div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="ten wide column">
      <div class='ui stackable two column grid'>
        <% @user.entries.each do |entry| %>
          <div class='column'>
            <div class="ui segment">
              <%= link_to show_entry_path(entry) do %>
                <%= image_tag(entry.avatar.url(:large), class: 'ui medium rounded image') %>
              <% end %><br>
              <div class="content">
                <h3 class='ui centered header'><%= entry.caption %></h3>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>